### ISSUE TITLE
Browser out of date

### ISSUE THREAD

**Issue by joroehr** [mykle1/MMM-ISS-Live#2]
Hi, 

module is working fine but i get the error message that my browser is out of date. Any recommendations to solve this?

BR

**Comment by mykle1** [comment]
Hi,

Yes, this started happening recently but it cannot be corrected by me because it's coming from the source. However, if you have the ability to "click", you can close the message. The module then performs as expected, even surviving several restarts. Unfortunately, the message will return eventually and you would have to click/close the message again. I'm sorry about that. I really love this module too. I do appreciate your interest, thanks.
