### ISSUE TITLE
Way to mute video volume?

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-ISS-Live#3]
is there an easy way to do this?

**Comment by ghost** [comment]
none of those methods work, ill look into it myself tonight, i dont feel like its a feature request since you should be able to do this already, like on any video app, or anything thats ever played any video for the last 100 years, i cant use this with anything else that involves audio with constant chatter in the background, like youtube, spotify, assistant, etc so you cant use this with voice which was intended when it was built, not a feature request since it effects the intended workings of the itself and other applications

**Comment by ghost** [comment]
put in 

iframe.setVolume = ("muted");

on line 38, havent heard them in an hour or so, hopefully that worked out

**Comment by ghost** [comment]
guess it didnt work they still talking

**Comment by mykle1** [comment]
I might have looked into it further until I read your response to my last post, you ungrateful whining bitch. Delete any modules of mine that you use so you have nothing to complain about.

**Comment by mykle1** [comment]
I might have looked into it further until I read your response to my last post, you ungrateful whining bitch. Delete any modules of mine that you use so you have nothing to complain about.

**Comment by mykle1** [comment]
I might have looked into it further until I read your response to my last post, you ungrateful whining bitch. Delete any modules of mine that you use so you have nothing to complain about.

**Comment by JoshuaShelswell** [comment]
> 
> 
> I might have looked into it further until I read your response to my last post, you ungrateful whining bitch. Delete any modules of mine that you use so you have nothing to complain about.

im sorry for irritating you if i somehow did, im autistic and people have to ask me what i mean when i say things sometimes i can see how you would take that, im trying to make the volume work on your application and im trying things myself, i might give a shot at rebuilding a module myself since none of the methods you posted worked, i think it has to do with the iframe, which you should be encouraging since im new to this, dont need to use profane languages or call people bitches either, its super unprofessional and makes people loose respect for you, im trying to bring up an issue that i and probably other people have with it since i have to mute the entire system to use it, im sorry you cant take any kinda constructive criticism and you cant discern whats a feature request vs how it was intended to run since you literally made functionalities in your code that verifies what it was intended for, didnt mean to insult or to piss you off or offend you, i already said that i appreciate your work in a post the other day, sorry if you're having issues but its not with me, im trying to make a christmas present for my partners mom and im out of time to fiddle with apps so that project will be in the new year if you dont feel like you want to pick it up regardless its an issue weather you like it or not, and ill work on whatever i want and report issues as much as i can since it helps the meta of all the projects going, i appreciate your work but if you are pissed off about people building things, bringing up an issue and trying to fix it maybe this isnt for you, not trying to piss you off, trying to resolve issues

**Comment by ghost** [comment]
reporting you for abuse, you dont know what you're doing and all you seem to do is insult people and delete comments, you're a trash programmer also that cant fix solutions or even find his own problems, have fun with your old self, ive moved onto react and built my own apps and copied yours because yours dont work and are generally garbage, peace

**Comment by ghost** [comment]
> I might have looked into it further until I read your response to my last post, you ungrateful whining bitch. Delete any modules of mine that you use so you have nothing to complain about.

awww look who cant be an adult, what are you like 60? grow up

**Comment by ghost** [comment]
and you should listen to your son, stop programming because you obviously cant do it lol, all the methods you pasted were from a google search lmao, you built your application (which im sure you just copied) so none of those work, enjoy reading

**Comment by ghost** [comment]
oh dont bother replying btw, unsubscribed to your notifications because you dont know how to fix anything and probably just copied all this code anyway, enjoy being mad at things for pretty much no reason, bye lol
